### PR TITLE
Deprecate OptimadeQueryWidget

### LINKED ISSUE #4: Deprecate OptimadeQueryWidget
The `OptimadeQueryWidget` is moving over to `aiidalab-widgets-base` (aiidalab/aiidalab-widgets-base#131). To keep a grace period, the widget will be imported from `aiidalab-widgets-base` and still be importable from this application, but with a deprecation warning.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #4.

It has moved to aiidalab-widgets-base.

**NOTE**: Should _not_ be merged until aiidalab/aiidalab-widgets-base#131 has been merged.

### CODE REVIEW

**Comment by CasperWA** [comment]
@yakutovicha This is now ready for review.

**Review by yakutovicha — COMMENTED** [review]
I cleaned up the notebook a bit more, see 2a765882968f1d2af04012401cceb95bef9ea432.

However, one typically shouldn't mix up things in one PR.

**Comment by CasperWA** [comment]
> I cleaned up the notebook a bit more, see [2a76588](https://github.com/aiidalab/aiidalab-optimade/commit/2a765882968f1d2af04012401cceb95bef9ea432).
> 
> However, one typically shouldn't mix up things in one PR.

Indeed, This would be better done in a separate PR, Do you mind opening one with these changes? If not, then let's just merge this in with two separate commits.

**Comment by yakutovicha** [comment]
> > I cleaned up the notebook a bit more, see [2a76588](https://github.com/aiidalab/aiidalab-optimade/commit/2a765882968f1d2af04012401cceb95bef9ea432).
> > However, one typically shouldn't mix up things in one PR.
> 
> Indeed, This would be better done in a separate PR, Do you mind opening one with these changes? If not, then let's just merge this in with two separate commits.

I can open, it is not a problem

**Pull request merged**
